apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "decrypt.fullname" . }}-resolver
  labels:
    {{- include "decrypt.labels" . | nindent 4 }}-resolver
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "decrypt.selectorLabels" . | nindent 6 }}-resolver
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "decrypt.selectorLabels" . | nindent 8 }}-resolver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "decrypt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.resolver.image.repository }}:{{ .Values.resolver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.resolver.image.pullPolicy }}
          env:
          - name: CTF_REMOTEURL
            value: "https://cryptic.xxxx.xxx.austrianopencloudcommunity.org"
          ports:
            - name: http
              containerPort: {{ .Values.resolver.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
